#!/usr/bin/env bash
#
# gen-environment-local.sh
# Generates docs/ENVIRONMENT.local.md filled with YOUR cluster's values.
#
# Why a script (not a pre-filled file): the sensitive identifiers (API URL,
# apps domain, hosts) are pulled directly from your cluster via `oc` and written
# locally. They never leave your machine. The non-sensitive decisions already
# made (operator pins, realm name, client IDs) are baked in below.
#
# Usage:
#   oc login ...                  # be logged in to the target cluster
#   ./scripts/gen-environment-local.sh
#
# The output file is gitignored. Re-run any time to refresh from the cluster.

set -euo pipefail

OUT="docs/ENVIRONMENT.local.md"

# Make sure we're at the repo root (docs/ exists)
if [[ ! -d docs ]]; then
  echo "Run this from the repo root (the folder containing docs/)." >&2
  exit 1
fi

# Require an active oc session
if ! oc whoami >/dev/null 2>&1; then
  echo "Not logged in. Run 'oc login ...' first." >&2
  exit 1
fi

echo "Collecting values from the cluster..."

OCP_VERSION="$(oc version -o json 2>/dev/null | python3 -c 'import sys,json;print(json.load(sys.stdin)["openshiftVersion"])' 2>/dev/null || echo 'TODO')"
API_URL="$(oc whoami --show-server 2>/dev/null || echo 'TODO')"
APPS_DOMAIN="$(oc get ingresses.config/cluster -o jsonpath='{.spec.domain}' 2>/dev/null || echo 'TODO')"
DEFAULT_SC="$(oc get storageclass -o jsonpath='{range .items[?(@.metadata.annotations.storageclass\.kubernetes\.io/is-default-class=="true")]}{.metadata.name}{end}' 2>/dev/null || echo 'TODO')"
if oc auth can-i create subscriptions.operators.coreos.com -n openshift-operators >/dev/null 2>&1; then
  CLUSTER_ADMIN="yes"
else
  CLUSTER_ADMIN="no / limited"
fi

# Derived hosts (best-effort guesses; confirmed after the foundation is installed)
KC_NS="showcase-keycloak"
DH_NS="showcase-devhub"

cat > "$OUT" <<EOF
# Environment Fact Sheet (LOCAL — real values, gitignored)

> Generated by scripts/gen-environment-local.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
> This file is in .gitignore and must never be committed. It holds sensitive
> identifiers (hosts, URLs). True secrets (passwords, client secrets, tokens) do
> NOT go here — they go in a local secret.env applied via
> \`oc create secret ... --dry-run=client -o yaml | oc apply -f -\`.

## 1. Cluster

| Item | Value |
|------|-------|
| OpenShift version | \`${OCP_VERSION}\` |
| Cluster API URL | \`${API_URL}\` |
| Apps wildcard domain | \`${APPS_DOMAIN}\` |
| Default StorageClass | \`${DEFAULT_SC}\` |
| Cluster admin available? | ${CLUSTER_ADMIN} |

## 2. Operators (pinned — phase 1)

\`installPlanApproval: Manual\`, pinned startingCSV. Confirmed against this cluster's catalog.

| Operator | Namespace | Channel | startingCSV | Phase |
|----------|-----------|---------|-------------|-------|
| Red Hat OpenShift GitOps | \`openshift-gitops-operator\` | \`gitops-1.20\` | \`openshift-gitops-operator.v1.20.4\` | 1 |
| Red Hat build of Keycloak | \`${KC_NS}\` | \`stable-v26.6\` | \`rhbk-operator.v26.6.3-opr.1\` | 1 |
| Red Hat Developer Hub | \`${DH_NS}\` | \`fast-1.10\` | \`rhdh-operator.v1.10.1\` | 1 |
| Connectivity Link (Kuadrant community) | \`kuadrant-system\` | \`stable\` | \`kuadrant-operator.v0.11.1\` | 2 (deferred) |

## 3. Namespaces

| Purpose | Namespace |
|---------|-----------|
| Argo CD / GitOps | \`openshift-gitops\` |
| Keycloak | \`${KC_NS}\` |
| Developer Hub | \`${DH_NS}\` |
| Connectivity Link | \`kuadrant-system\` (phase 2) |
| Solutions deploy into | \`showcase-*\` |

## 4. Identity — Keycloak

| Item | Value | Notes |
|------|-------|-------|
| Realm name | \`showcase\` | decided |
| Keycloak route/host | \`TODO\` | after install: \`keycloak.${APPS_DOMAIN}\` (confirm) |
| OIDC issuer URL | \`TODO\` | after install: \`https://<keycloak-host>/realms/showcase\` |
| Admin user | \`TODO\` | value via Secret, NOT here |

### OIDC clients (IDs only — secrets via secret.env, never here)

| Client ID | Used by | Phase |
|-----------|---------|-------|
| \`developer-hub\` | Developer Hub login | 1 |
| \`connectivity-link\` | API auth policies | 2 |

## 5. API exposure — Connectivity Link (phase 2)

| Item | Value |
|------|-------|
| (deferred) | only Kuadrant community v0.11.1 in catalog — see foundation/connectivity-link/ |

## 6. Catalog — Developer Hub

| Item | Value | Notes |
|------|-------|-------|
| Developer Hub route/host | \`TODO\` | after install: \`devhub.${APPS_DOMAIN}\` (confirm) |
| Auth provider | Keycloak (OIDC), client \`developer-hub\` | |

## 7. Git

| Item | Value |
|------|-------|
| Repo URL | \`https://github.com/sandrotanaka/showcase-app-platform.git\` |
| Default branch | \`main\` |

## Open decisions / notes

- Connectivity Link deferred to phase 2 (workshop cluster lacks the Red Hat product).
- Hosts/issuer in §4/§6 are filled after the foundation is installed.
EOF

echo "Wrote $OUT"
echo "Reminder: this file is gitignored and must not be committed."
